In [43]:
import numpy as np
def neighborhood(n, cell):
    """
    Function to find all the neighbours of the cell
    """
    neighbors = []
    if cell[0] + 1 < n:
        neighbors.append((cell[0]+1, cell[1]))
        if cell[1] - 1 >= 0:
            neighbors.append((cell[0]+1, cell[1]-1))
    if cell[0] - 1 >= 0:
        neighbors.append((cell[0]-1, cell[1]))
        if cell[1] + 1 < n:
            neighbors.append((cell[0]-1, cell[1]+1))
    if cell[1] + 1 < n:
        neighbors.append((cell[0], cell[1]+1))
    if cell[1] - 1 >= 0:
        neighbors.append((cell[0], cell[1]-1))
    return neighbors
def get_neighbors(n, coordinates):
        """Gets all the neighbouring cells of a given cell
        Args:
            coordinates (tuple): Cell (x, y) coordinates
        Returns:
            list: List of neighbouring cell coordinates tuples
        """
        (cx,cy) = coordinates
        neighbors = []
        if cx-1 >= 0: neighbors.append((cx-1,cy))
        if cx+1 < n: neighbors.append((cx+1,cy))
        if cx-1 >= 0 and cy+1 <= n-1: neighbors.append((cx-1,cy+1))
        if cx+1 < n and cy-1 >= 0: neighbors.append((cx+1,cy-1))
        if cy+1 < n: neighbors.append((cx,cy+1))
        if cy-1 >= 0: neighbors.append((cx,cy-1))

        return neighbors
def border(n, color, move):
        """Checks if move is on the border of the board
        Args:
            color (int): Player to move
            move (tuple): Move (x, y) which is taken
        Returns:
            bool: True if the move is on the border and False if not
        """
        (nx, ny) = move
        return (color == 2 and nx == n-1) or (color == 1 and ny == n-1)

def traverse(board, player, move, visited):
    if board[move[0]][move[1]] != player or (move in visited and visited[move]):
        # print(move)
        return False
    # if border(len(board),1, move):
    #     return True
    if player == 1 and move[0] == len(board)-1:
        return True
    if player == 2 and move[1] == len(board)-1:
        return True
    # If not then this cell is visited
    visited[move] = True
    print(visited)
    # Traverse the neighbouring cells
    for neighbor in get_neighbors(len(board), move):
        if traverse(board, player, neighbor, visited):
            return True
    return False

def check_winning_condition(board, player, endlist):
    for i in range(len(board)):
        if player == 1:
            move = (0, i)
        else:
            move = (i, 0)
        visited = {}
        if traverse(board, player, move, visited):
            # print(move)
            return True
    return False

b = np.array([[0,0,1], [1,1,2],[2,0,0]])
print(b)
print(len(b))
print(check_winning_condition(b, 1, [(2,0),(2,1), (2,2)]))

[[0 0 1]
 [1 1 2]
 [2 0 0]]
3
True
